// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJvEJkfixjMH9dp7t9zD-AY3Vk4LTfyDc',
    appId: '1:141018243221:android:00566c712a27848f2e7b9c',
    messagingSenderId: '141018243221',
    projectId: 'alumni-app-65e09',
    storageBucket: 'alumni-app-65e09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZaU35sX-pxscNEznfDQmiHdO81V9l0w',
    appId: '1:141018243221:ios:d55b40da49d641d12e7b9c',
    messagingSenderId: '141018243221',
    projectId: 'alumni-app-65e09',
    storageBucket: 'alumni-app-65e09.firebasestorage.app',
    androidClientId: '141018243221-d8cgngn9ja11s2ngga027c7coh7opseg.apps.googleusercontent.com',
    iosClientId: '141018243221-9rfrjk9p0hfpqd8egibf01g3sst7r331.apps.googleusercontent.com',
    iosBundleId: 'com.example.components',
  );

}